# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rn_firebase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn_firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'rn_firebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rn_firebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
